### ISSUE TITLE
Initial Editor Checklist

### ISSUE THREAD

**Issue by leibatt** [journalovi/2024-Cashman-PAC-learning-game#1]
- [ ] Check that the HTML version is in the repo as index.html and renders to the JoVI format (refer to https://github.com/journalovi/jovi-template-quarto)
- [x] Article uses a format something similar to the template
- [x] Includes author information
- [x] Includes abstract
- [x] Includes the required paper sections
   - [x] Table of contents
   - [x] Research materials
   - [x] Authorship
   - [x] License
   - [x] Conflicts of Interest
- [x] Add a notice infobox at the top that the paper is under review w/ link to github issues above the abstract. In Quarto this looks like:
   ```
   ::: {.callout-important appearance="simple"}
   ## Under Review {.unnumbered}
   This paper is under review on the experimental track of the [Journal of Visualization and Interaction](https://www.journalovi.org/).
   :::
   ```
- [x] Set up github pages
   - [x] Settings -> Actions -> General -> Allow journalovi, and select non-journalovi, actions. Enter: 
      `actions/*,quarto-dev/*`
      ![image](https://github.com/journalovi/2023-park-gatherplots/assets/6345019/05018b2f-f00e-4019-92de-cced0aab0d72)
   - [x] If using Quarto:
      - [ ] clone the repo locally
      - [ ] run this command in the repo directory:
         ```
         quarto publish gh-pages index.qmd
         ```
- [x] From the main repo page, click the settings gear icon next to "About" on the right. 
   - [x] Under "Description" enter "UNDER REVIEW"
   - [x] Under "Website" tick "Use Your Github Pages Website".
- [x] Verify the publishing workflow works. On the repo page, go to Actions and click on the "XXX Publish" (XXX = Quarto/Idyll/etc) workflow on the left, then click Run Workflow and run it.
   - [x] When this completes, check that the "pages build and deployment" action is successful.
   - [x] Check that the article is visible at the github.io address.
- [x] Edit README.md and add the following at the very top:
   ````
   ```diff
   ! This paper is under review on the experimental track of the Journal of Visualization and Interaction.
   ```
   ````
- [ ] Ensure all appropriate supplemental materials are included: e.g. experimental data, experimental analysis code, source code for artifacts, etc. For a full list of requirements see the [transparency section of the author guide](https://www.journalovi.org/author-guide.html#transparency-requirements)
  - [x] #2
  - [ ] Check they are listed in the abstract and the required Materials section of the paper
- [x] If anything in the above list is missing (required paper sections, supplemental materials, etc), create an issue tagging the authors and ask them to add those materials (do this after sending them the intial review email).

**Comment by dylancashman** [comment]
Hi @leibatt ,
Thank you for organizing my review!  I noticed that a review has been completed.  I just wanted to double check my responsibilities and the ensuing timeline.  

1. Am I responsible for fixing all of the missing checkboxes on this checklist?
2. I understand the accessibility review is still coming.  Are there any other reviews that I should wait for?  
3. Do you know when my revisions are expected to be done?

Thanks!  Very excited for this and I'm enjoying the issues-based form of reviewing so far.

**Comment by leibatt** [comment]
Thanks for following up on this! We are still in the process of getting all the reviews. To answer your questions:

> 1. Am I responsible for fixing all of the missing checkboxes on this checklist?

I would only be concerned with the last few checkboxes about supplemental materials. I've opened a separate issue connected to this one and assigned you to it (see #2).

> 2. I understand the accessibility review is still coming.  Are there any other reviews that I should wait for?

Yes, there will be 3 reviews in total. We're still waiting for two more, not including the accessibility review.

> 3. Do you know when my revisions are expected to be done?

I am double checking this and will get back to you with an answer asap!

> Thanks! Very excited for this and I'm enjoying the issues-based form of reviewing so far.

I'm also super excited! I'm happy to help and thanks so much for submitting to JoVI! :)

**Comment by leibatt** [comment]
@dylancashman following up: after the reviews are all in, the current process is to have revisions within 3 months. However, this is certainly not a restriction. Authors are welcome to respond to reviews and work on revisions sooner if preferred. It can also be a bit more of a back and forth dialogue than a traditional revision cycle, if needed.

Here is an example of the review and revision process for our first experimental track paper, if it would be helpful to see a live example: https://github.com/journalovi/2023-park-gatherplots/issues

**Comment by leibatt** [comment]
@dylancashman can you add the new OSF link to the abstract?
